accounts/urls.py
from django.urls import path
from accounts.views import (login_view, logout_view,
                            register_view, update_view,
                            delete_view, contact)

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('update/', update_view, name='update'),
    path('delete/', delete_view, name='delete'),
    path('contact/', contact, name='contact'),
]

scraping/urls.py
from django.urls import path
from scraping.views import VacancyListView, HomeView

app_name = 'scraping'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('list/', VacancyListView.as_view(), name='list'),
]

scraping_service/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scraping.urls')),
    path('accounts/', include('accounts.urls')),
]

scraping/models.py
import jsonfield  # Для цього потрібно поставити бібліотеку
from django.db import models


def default_urls():
    """Передача урлов для таблиці URL"""
    return {"work": "", "rabota": "", "dou": "", "djinni": ""}


class City(models.Model):
    """Назва міста де шукаєм вакансію"""
    name = models.CharField(max_length=50, verbose_name='назва населеного пункту', unique=True)
    slug = models.SlugField(max_length=50, blank=True, unique=True)

    class Meta:
        verbose_name = 'назва населеного пункту'
        verbose_name_plural = 'назва населених пунктів'

    def __str__(self):
        return self.name


class Language(models.Model):
    """Мова програмування, для якої шукаєм вакансію"""
    name = models.CharField(max_length=50, verbose_name='мова програмування', unique=True)
    slug = models.SlugField(max_length=50, blank=True, unique=True)

    class Meta:
        verbose_name = 'мова програмування'
        verbose_name_plural = 'мови програмування'

    def __str__(self):
        return self.name


class Vacancy(models.Model):
    """Збережені вакансії"""
    url = models.URLField(unique=True)
    title = models.CharField(max_length=250, verbose_name='заголовок вакансії')
    company = models.CharField(max_length=250, verbose_name='компанія')
    description = models.TextField(verbose_name='опис вакансії')
    city = models.ForeignKey('City', on_delete=models.CASCADE,
                             verbose_name='місто', related_name='vacancies')
    language = models.ForeignKey('Language', on_delete=models.CASCADE,
                                 verbose_name='мова програмування')
    timestamp = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'вакансія'
        verbose_name_plural = 'вакансії'
        ordering = ['-timestamp']

    def __str__(self):
        return self.title


class Error(models.Model):
    """Для помилок"""
    timestamp = models.DateField(auto_now_add=True)
    data = jsonfield.JSONField()

    def __str__(self):
        return str(self.timestamp)


class Url(models.Model):
    """Для збереження адресс для парсерів"""
    city = models.ForeignKey('City', on_delete=models.CASCADE, verbose_name='місто')
    language = models.ForeignKey('Language', on_delete=models.CASCADE, verbose_name='мова програмування')
    url_data = jsonfield.JSONField(default=default_urls)

    class Meta:
        unique_together = ("city", "language")  # Для унікальності запису

scraping/forms.py
from django import forms

from scraping.models import City, Language


class FindForm(forms.Form):
    """Пошук по містам та спеціальностям із БД з вибором"""
    city = forms.ModelChoiceField(queryset=City.objects.all(), to_field_name="slug", required=False,
                                  widget=forms.Select(attrs={'class': 'form-control'}), label='Виберіть місто')
    language = forms.ModelChoiceField(queryset=Language.objects.all(), to_field_name="slug", required=False,
                                      widget=forms.Select(attrs={'class': 'form-control'}), label='Спеціальність')

scraping/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView

from .forms import FindForm
from .models import Vacancy


class HomeView(View):
    """Пошук"""
    form_class = FindForm
    initial = {'key': 'value'}
    template_name = 'scraping/home.html'

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})


class VacancyListView(ListView):
    """Список вакансій"""
    model = Vacancy
    template_name = 'scraping/list.html'
    form = FindForm()
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """Те, що ми перекидуєм в контекст"""
        context = super().get_context_data(**kwargs)
        context['city'] = self.request.GET.get('city')
        context['language'] = self.request.GET.get('language')
        context['form'] = self.form
        return context

    def get_queryset(self):
        city = self.request.GET.get('city')
        language = self.request.GET.get('language')
        qs = []
        if city or language:
            _filter = {}
            if city:
                _filter['city__slug'] = city
            if language:
                _filter['language__slug'] = language
            qs = Vacancy.objects.filter(**_filter).select_related('city', 'language')
        return qs

scraping/templates/scraping/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row">
    <div class="col"><h2 class=" text-center my-3">Сервіс по сбору та розсилці вакансій</h2></div>
</div>
<div class="row ">
    <div class="col-md-8 mx-auto my-2">
        <p class="">
            Кожний день ми аналізуємо сайти із вакансіями, згідно налаштувань наших подписчиків.
            Всі підходящі вакансії, які були опубліковані на  сайтах за останні сутки,
            записуються в базу данних і розсилаються автоматично, згідно їх налаштувань.
            Ви можете продивитись актуальні вакансії, просто вибрав необхідне місто чи спеціальність.
            Або, пройшовши не важку <a href="{% url 'accounts:register' %}"> регістрацію</a>,
            отримувати кожний день лист зі списком нових вакансій за останні сутки, згідно Ваших налаштувать.
        </p>
        <form method="GET" action="{% url 'scraping:list' %}">
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Пошук</button>
        </form>
    </div>
</div>
{% endblock %}

scraping/templates/scraping/list.html
{% extends "base.html" %}

{% block title %} Пропозиції {% endblock %}

{% block content %}


{% if object_list %}
 <h3 class="my-4 text-center">Результати пошуку згідно вашого запиту</h3>
    {% for obj in  object_list %}
        <div class="card my-3">
          <h5 class="card-header"><a href="{{ obj.url }}">{{ obj.title }}</a></h5>
          <div class="card-body">
             <p class="card-text">{{ obj.description }}</p>
              <p><strong>{{ obj.company }}</strong></p>
              <p>{{obj.city.name }} | {{obj.language.name }} |
                  <small>{{obj.timestamp|date:"d-m-Y" }}</small></p>
          </div>
        </div>
    {% endfor %}

        <div class="row">
            <div class="col">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                      {% if page_obj.has_previous %}
                          <li class="page-item">
                                <a class="page-link" href="?city={{city}}&language={{ language }}&page=1" aria-label="Попередня">
                                <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                      {% endif %}
                      {% for page in page_obj.paginator.page_range %}
                          <li class="page-item {% if page == page_obj.number %} active {% endif %}">
                              <a class="page-link" href="?city={{city}}&language={{ language }}&page={{page}}">{{page}}</a>
                          </li>
                      {% endfor %}
                      {% if page_obj.has_next %}
                          <li class="page-item">
                          <a class="page-link" href="?city={{city}}&language={{ language }}&page={{ page_obj.next_page_number }}" aria-label="Наступна">
                            <span aria-hidden="true">&raquo;</span>
                          </a>
                        </li>
                      {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
{% else %}
        <h3 class="my-4 text-center">Нажаль, по Вашому запросу, нічого не знайдено.</h3>
{% endif %}

<div class="row ">
    <div class="col-md-6 mx-auto my-3">
        <h4 class="my-4 text-center">Новий пошук</h4>
    <form method="GET" action="{% url 'scraping:list' %}">
        <div class="form-group">
        {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Пошук</button>
    </form>
    </div>
</div>

{% endblock %}