accounts/urls.py
from django.urls import path
from accounts.views import (login_view, logout_view,
                            register_view, update_view,
                            delete_view, contact)

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('update/', update_view, name='update'),
    path('delete/', delete_view, name='delete'),
    path('contact/', contact, name='contact'),
]

scraping_service/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scraping.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email, password=password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    city = models.ForeignKey('scraping.City', on_delete=models.SET_NULL, null=True, blank=True)
    language = models.ForeignKey('scraping.Language', on_delete=models.SET_NULL, null=True, blank=True)
    send_email = models.BooleanField(default=True)
    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'аккаунт'
        verbose_name_plural = 'аккаунти'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.hashers import check_password

from scraping.models import City, Language

User = get_user_model()


class UserLoginForm(forms.Form):
    """Форма входу на сайт"""
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self, *args, **kwargs):
        """Перевірка на валідність"""
        email = self.cleaned_data.get('email').strip()
        password = self.cleaned_data.get('password').strip()

        if email and password:
            qs = User.objects.filter(email=email)
            if not qs.exists():
                raise forms.ValidationError('Такий користувач відсутній!')
            if not check_password(password, qs[0].password):
                raise forms.ValidationError('Невірний пароль!')
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('Данний аккаунт заблоковано')
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(forms.ModelForm):
    """Форма регістрації"""
    email = forms.EmailField(label='Введіть email',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Введіть пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Введіть пароль ще раз',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        data = self.cleaned_data
        if data['password'] != data['password2']:
            raise forms.ValidationError('Паролі не співпадають!')
        return data['password2']


class UserUpdateForm(forms.Form):
    """Данні аккаунта"""
    city = forms.ModelChoiceField(queryset=City.objects.all(), to_field_name="slug", required=True,
                                  widget=forms.Select(attrs={'class': 'form-control'}), label='місто')
    language = forms.ModelChoiceField(queryset=Language.objects.all(), to_field_name="slug", required=True,
                                      widget=forms.Select(attrs={'class': 'form-control'}), label='спеціальність')
    send_email = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='отримати розсилку?')

    class Meta:
        model = User
        fields = ('city', 'language', 'send_email')


class ContactForm(forms.Form):
    """Форма зворотнього звязку"""
    city = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}), label='місто')
    language = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}),
                               label='спеціальність')
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}),
                             label='введіть email')

accounts/views.py
import datetime as dt
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages

from accounts.forms import (UserLoginForm, UserRegistrationForm,
                            UserUpdateForm, ContactForm)
from scraping.models import Error

User = get_user_model()


def login_view(request):
    """Ідентифікація"""
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        data = form.cleaned_data
        email = data.get('email')
        password = data.get('password')
        user = authenticate(request, email=email, password=password)
        login(request, user)
        return redirect('/')
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    """Вихід із системи"""
    logout(request)
    return redirect('/')


def register_view(request):
    """Регістрація"""
    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        messages.success(request, 'Користувач добавлений в систему.')
        return render(request, 'accounts/register_done.html', {'new_user': new_user})
    return render(request, 'accounts/register.html', {'form': form})


def update_view(request):
    """Зміна налаштувань з перевіркою на валідність користувача"""
    contact_form = ContactForm()
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            form = UserUpdateForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                user.city = data['city']
                user.language = data['language']
                user.send_email = data['send_email']
                user.save()
                messages.success(request, 'Данні збережені.')
                return redirect('accounts:update')

        form = UserUpdateForm(initial={'city': user.city,
                                       'language': user.language,
                                       'send_email': user.send_email})
        return render(request, 'accounts/update.html',
                      {'form': form, 'contact_form': contact_form})
    else:
        return redirect('accounts:login')


def delete_view(request):
    """Видалення користувача"""
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            qs = User.objects.get(pk=user.pk)
            qs.delete()
            messages.error(request, 'Користувача видалено :(')
    return redirect('/')


def contact(request):
    """Зворотній звязок"""
    if request.method == 'POST':
        contact_form = ContactForm(request.POST or None)
        if contact_form.is_valid():
            data = contact_form.cleaned_data
            city = data.get('city')
            language = data.get('language')
            email = data.get('email')
            qs = Error.objects.filter(timestamp=dt.date.today())
            if qs.exists():
                err = qs.first()
                data = err.data.get('user_data', [])
                data.append({'city': city, 'email': email, 'language': language})
                err.data['user_data'] = data
                err.save()
            else:
                data = [{'city': city, 'email': email, 'language': language}]
                Error(data=f"user_data:{data}").save()
            messages.success(request, 'Данні відправлені адміністрації.')
            return redirect('accounts:update')
        else:
            return redirect('accounts:update')
    else:
        return redirect('accounts:login')

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}

<div class="row ">
    <div class="col-md-8 mx-auto">
        <h4 class="my-2">Форма входу</h4>
    <form method="POST" action="">{% csrf_token %}
        <div class="form-group">
        {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Увійти</button>
    </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block title %} Register {% endblock %}

{% block content %}

<div class="row ">
    <div class="col-md-8 mx-auto">
        <h4 class="my-2">Реєстрація нового користувача</h4>
    <form method="POST" action="">{% csrf_token %}
        <div class="form-group">
        {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Зареєструватися</button>
    </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register_done.html
{% extends "base.html" %}

{% block title %} Register {% endblock %}

{% block content %}

<div class="row ">
    <div class="col-md-8 mx-auto">
        <h4 class="my-2">Вітаємо нового користувача {{ new_user.email}}</h4>
        <p>Ви зареєструвались в системі.
            Тепер Ви можете <a href="{% url 'accounts:login' %} ">увійти.</a>
        </p>

    </div>
</div>

{% endblock %}

accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block title %} Register {% endblock %}

{% block content %}

<div class="row ">
    <div class="col-md-8 mx-auto">
        <h4 class="my-2">Настройки</h4>
    <form method="POST" action="">{% csrf_token %}
        <div class="form-group">
        {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Зберегти</button>
    </form>
    <form method="POST" action="{% url 'accounts:delete' %} ">{% csrf_token %}
        <button type="submit" class="btn btn-danger my-3">Видалити</button>
    </form>
    </div>
</div>

<div class="row my-5">
    <div class="col-md-8 mx-auto">
        <p class="my-2">Якщо ви не знайшли підходящий вам набір: Місто-Спеціальність,
            Ви можете заповнити форму нижче з Вашими побажаннямии. Посля того,
            як необхідні данні будуть добавлені, Ви отримаєте листа на указаний Вами email.</p>
        <p>
          <button class="btn btn-success"
                  type="button" data-toggle="collapse"
                  data-target="#collapsed" aria-expanded="false"
                  aria-controls="collapseExample">
            Показати форму
          </button>
        </p>
        <div class="collapse" id="collapsed">
          <div class="card card-body">
              <form method="POST" action="{% url 'accounts:contact' %} ">{% csrf_token %}
                <div class="form-group">
                {{ contact_form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Відправити</button>
              </form>
          </div>
        </div>


    </div>
</div>
{% endblock %}